/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ModuleGraph {
  graph: Record<string, Array<string>>
  basePath: string
  entryPoints: Array<string>
  modules: Record<string, Module>
}
export interface PackageJson {
  name?: string
  version?: string
  path: string
  href: string
}
export interface Module {
  href: string
  pathname: string
  path: string
  importedBy: Array<string>
  packageJson: PackageJson
  source: string
}
export interface Plugin {
  name?: string
  start?: (...args: any[]) => any
  analyze?: (...args: any[]) => any
  handleImport?: (...args: any[]) => any
}
export function createModuleGraph(
  entryPoints: Array<string>,
  basePath: string,
  conditionNames: Array<string>,
  builtinModules: Array<string>,
  ignoreExternal: boolean,
  plugins: Array<Plugin>,
): ModuleGraph
